" Install plugins first
source ~/.vim/config/plugins.vim

" Plugin settings
source ~/.vim/config/plugins/index.vim

" Everything else
source ~/.vim/config/abbreviations.vim
source ~/.vim/config/editor.vim
source ~/.vim/config/mappings.vim
