source ~/.vim/config/plugins/autosave.vim
source ~/.vim/config/plugins/gitgutter.vim
source ~/.vim/config/plugins/nerd-tree.vim
source ~/.vim/config/plugins/promiscuous.vim
source ~/.vim/config/plugins/search.vim
source ~/.vim/config/plugins/splitjoin.vim
source ~/.vim/config/plugins/syntastic.vim
source ~/.vim/config/plugins/tsuquyomi.vim
source ~/.vim/config/plugins/vim-markdown.vim
source ~/.vim/config/plugins/wintabs.vim
